<?php
$this->htmlElement('body')->appendAttribute('class', ' inverse-properties');
?>

<?php echo $this->pageTitle($this->translate('Properties'), 1, $this->translate('Inverse properties'), $resourceTemplate->getLabel()); ?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formElement($form->get('form_csrf')); ?>

<div id="page-actions">
    <a class="button" href="<?php echo $this->escapeHtml($this->url('admin/inverse-properties', [], true)); ?>"><?php echo $this->translate('Cancel'); ?></a>
    <input type="submit" value="<?php echo $this->escapeHtml($this->translate('Submit')); ?>">
</div>

<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Property'); ?></th>
            <th><?php echo $this->translate('Alternate label'); ?></th>
            <th><?php echo $this->translate('Inverse property'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($resourceTemplate->getResourceTemplateProperties() as $resourceTemplateProperty): ?>
        <tr>
            <td><?php echo $resourceTemplateProperty->getProperty()->getLabel(); ?></td>
            <td><?php echo $resourceTemplateProperty->getAlternateLabel(); ?></td>
            <td><?php echo $this->propertySelect([
                'name' => sprintf('inverse_property_ids[%s]', $resourceTemplateProperty->getId()),
                'options' => [
                    'empty_option' => ''
                ],
                'attributes' => [
                    'class' => 'chosen-select',
                    'data-placeholder' => 'Select property…', // @translate
                    'value' => $inversePropertyIds[$resourceTemplateProperty->getId()] ?? '',
                ],
            ]); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->form()->closeTag(); ?>
