<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/admin/inverse-properties.css', 'InverseProperties'));
$this->htmlElement('body')->appendAttribute('class', 'inverse-properties');
$resourceTemplatePorperties = $resourceTemplate->getResourceTemplateProperties();
?>

<?php echo $this->pageTitle($this->translate('Properties'), 1, $this->translate('Inverse properties'), $resourceTemplate->getLabel()); ?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formElement($form->get('form_csrf')); ?>

<div id="page-actions">
    <input type="submit" value="<?php echo $this->escapeHtml($this->translate('Submit')); ?>">
</div>

<div class="breadcrumbs">
    <?php echo $this->hyperlink($this->translate('Resource templates'), $this->url('admin/inverse-properties-resource-template')); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Properties'), $this->url(null, ['action' => 'show'], true)); ?>
    <div class="separator"></div>
    Edit
</div>

<?php if ($resourceTemplatePorperties): ?>
<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Property'); ?></th>
            <th><?php echo $this->translate('Inverse property'); ?></th>
            <th><?php echo $this->translate('Alternate label'); ?></th>
            <th><?php echo $this->translate('Data types'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($resourceTemplatePorperties as $resourceTemplateProperty): ?>
        <?php
        $property = $resourceTemplateProperty->getProperty();
        $inverseProperty = $inverseProperties[$resourceTemplateProperty->getId()] ?? null;
        ?>
        <tr>
            <td><?php echo sprintf('%s : %s', $property->getVocabulary()->getLabel(), sprintf('<strong>%s</strong>', $property->getLabel())); ?></td>
            <td><?php echo $this->propertySelect([
                'name' => sprintf('inverse_property_ids[%s]', $resourceTemplateProperty->getId()),
                'options' => [
                    'empty_option' => ''
                ],
                'attributes' => [
                    'class' => 'chosen-select',
                    'data-placeholder' => 'Select property…', // @translate
                    'value' => $inverseProperty ? $inverseProperty->getId() : '',
                ],
            ]); ?></td>
            <td><?php echo $resourceTemplateProperty->getAlternateLabel(); ?></td>
            <td>
                <?php foreach ($resourceTemplateProperty->getDataType() as $dataType): ?>
                <?php echo $this->dataType()->getLabel($dataType); ?><br>
                <?php endforeach; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<div class="no-resources">
    <p><?php echo $this->translate('No resource template properties found.'); ?></p>
</div>
<?php endif; ?>

<?php echo $this->form()->closeTag(); ?>
